buses/urls.py
from django.urls import include, path
from django.contrib import admin
from api import api

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api/", include(api.router.urls)),
    path("", include("busstops.urls")),
]


handler404 = "busstops.views.not_found"
handler500 = "busstops.views.error"

fares/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index),
    path("datasets/<int:pk>", views.DataSetDetailView.as_view(), name="dataset_detail"),
    path("tariffs/<int:pk>", views.TariffDetailView.as_view(), name="tariff_detail"),
    path("tables/<int:pk>", views.FareTableDetailView.as_view(), name="table_detail"),
]

vosa/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("licences/<slug>", views.LicenceView.as_view(), name="licence_detail"),
    path(
        "registrations/<path:slug>",
        views.RegistrationView.as_view(),
        name="registration_detail",
    ),
    path("licences/<licence_number>/rss", views.LicenceFeed()),
    path("areas/<licence_number>/rss", views.AreaFeed()),
]

fares/models.py
from functools import cached_property

from django.contrib.postgres.fields import DateTimeRangeField
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from django.utils.text import camel_case_to_spaces

# class Currency(models.TextChoices):
#     GBP = "GBP", "Pound Sterling"
#     EUR = "EUR", "Euro"


# currency = models.CharField(
#     max_length=3,
#     choices=Currency.choices,
#     default=Currency.GBP,
# )


class DataSet(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(blank=True)
    description = models.CharField(max_length=255, blank=True)
    operators = models.ManyToManyField("busstops.Operator", blank=True)
    datetime = models.DateTimeField(null=True, blank=True)
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("dataset_detail", args=(self.id,))

    def nice_name(self):
        return self.name.split("_", 1)[0]

    def credit(self):
        text = self.nice_name()

        if self.url:
            if "bus-data.dft.gov.uk" in self.url:
                text = f"{text}/Bus Open Data Service"

            text = format_html('<a href="{}" rel="nofollow">{}</a>', self.url, text)

        if self.datetime:
            text = f"{text}, {self.datetime:%-d %B %Y}"

        return mark_safe(f'<p class="credit">Fares data from {text}</p>')


class TimeInterval(models.Model):
    code = models.CharField(max_length=255, blank=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.description


class SalesOfferPackage(models.Model):
    code = models.CharField(max_length=255, blank=True)
    name = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    cash = models.BooleanField(default=False)
    contactless = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class PreassignedFareProduct(models.Model):
    code = models.CharField(max_length=140, blank=True)
    name = models.CharField(max_length=140, blank=True)
    charging_moment = models.CharField(max_length=25, blank=True)
    tariff_basis = models.CharField(max_length=25)


class UserProfile(models.Model):
    code = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    proof_required = models.CharField(max_length=255, blank=True)
    discount_basis = models.CharField(max_length=255, blank=True)
    min_age = models.PositiveSmallIntegerField(null=True, blank=True)
    max_age = models.PositiveSmallIntegerField(null=True, blank=True)

    def __str__(self):
        return camel_case_to_spaces(self.name)


class TypeOfTariff(models.TextChoices):
    # DISTANCE_KILOMETERS = "Distance_kilometers", "Kilometer Distance Kilometers"
    # FLAT = "flat", "Flat"
    POINT_TO_PONT = "point_to_point", "Point to point"
    ZONAL = "zonal", "Zonal"
    # SECTION = "section", "Section"    # BANDED = "banded", "Section"
    # STORED_VALUE = "stored_value", "Stored value"
    # MULTITRIP = "multitrip", "Multitrip carnet"


class Tariff(models.Model):
    code = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    services = models.ManyToManyField("busstops.Service", blank=True)
    operators = models.ManyToManyField("busstops.Operator", blank=True)
    source = models.ForeignKey(DataSet, models.CASCADE)
    filename = models.CharField(max_length=255)
    user_profile = models.ForeignKey(UserProfile, models.CASCADE, null=True, blank=True)
    trip_type = models.CharField(max_length=255, blank=True)
    valid_between = DateTimeRangeField(null=True, blank=True)
    type_of_tariff = models.CharField(
        max_length=19, choices=TypeOfTariff.choices, blank=True
    )
    access_zones = models.ManyToManyField("FareZone", blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("tariff_detail", args=(self.id,))

    class Meta:
        unique_together = ("source", "filename", "code")


class Price(models.Model):
    amount = models.DecimalField(max_digits=6, decimal_places=2)  # maximum £9999.99
    time_interval = models.ForeignKey(
        TimeInterval, models.CASCADE, null=True, blank=True
    )
    user_profile = models.ForeignKey(UserProfile, models.CASCADE, null=True, blank=True)
    sales_offer_package = models.ForeignKey(
        SalesOfferPackage, models.CASCADE, null=True, blank=True
    )
    tariff = models.ForeignKey(Tariff, models.CASCADE, null=True, blank=True)

    def __str__(self):
        if self.amount and self.amount >= 10:
            return str(self.amount).removesuffix(".00")
        return str(self.amount)


class FareTable(models.Model):
    code = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    user_profile = models.ForeignKey(UserProfile, models.CASCADE, null=True, blank=True)
    sales_offer_package = models.ForeignKey(
        SalesOfferPackage, models.CASCADE, null=True, blank=True
    )
    preassigned_fare_product = models.ForeignKey(
        PreassignedFareProduct, models.CASCADE, null=True, blank=True
    )
    tariff = models.ForeignKey(Tariff, models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("table_detail", args=(self.id,))

    @cached_property
    def is_triangular(self):
        cols = [col.name for col in self.column_set.all()]
        rows = [row.name for row in self.row_set.all()]
        rows.reverse()
        if len(cols) == len(rows):
            if cols[1:] == rows[:-1]:
                return True

    def columns(self):
        return self.column_set.all()

    def rows(self):
        cols = {col.id: col for col in self.column_set.all()}

        rows = list(self.row_set.all())
        for row in rows:
            for cell in row.cell_set.all():
                cell.column = cols[cell.column_id]
        if self.is_triangular:
            i = 0
            for row in rows:
                i += 1
                row.colspan = i
            rows.reverse()

        return rows


class FareZone(models.Model):
    code = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    stops = models.ManyToManyField("busstops.StopPoint", blank=True)
    source = models.ForeignKey(DataSet, models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name


class DistanceMatrixElement(models.Model):
    code = models.CharField(max_length=255)
    price = models.ForeignKey(Price, models.CASCADE)
    start_zone = models.ForeignKey(FareZone, models.CASCADE, related_name="starting")
    end_zone = models.ForeignKey(FareZone, models.CASCADE, related_name="ending")
    tariff = models.ForeignKey(Tariff, models.CASCADE)

    def html(self):
        if self.tariff.user_profile:
            tariff = self.tariff.user_profile
            if self.tariff.trip_type:
                tariff = f"{tariff} {self.tariff.trip_type}"
        else:
            tariff = self.tariff

        return f"{tariff}: £{self.price.amount}"

    def __str__(self):
        return self.code


class Column(models.Model):
    table = models.ForeignKey(FareTable, models.CASCADE)
    code = models.CharField(max_length=255, blank=True)
    name = models.CharField(max_length=255)
    order = models.PositiveSmallIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class Row(models.Model):
    table = models.ForeignKey(FareTable, models.CASCADE)
    code = models.CharField(max_length=255, blank=True)
    name = models.CharField(max_length=255)
    order = models.PositiveSmallIntegerField(null=True, blank=True)

    def cells(self):
        prev_order = 0
        for cell in self.cell_set.all():
            while cell.column.order - prev_order > 1:
                yield None
                prev_order += 1
            yield cell
            prev_order = cell.column.order
        while prev_order <= (len(self.table.row_set.all()) - self.order):
            yield None
            prev_order += 1
        # return self.cell_set.all()

    def __str__(self):
        return self.name


class Cell(models.Model):
    column = models.ForeignKey(Column, models.CASCADE)
    row = models.ForeignKey(Row, models.CASCADE)
    distance_matrix_element = models.ForeignKey(
        DistanceMatrixElement, models.CASCADE, null=True
    )
    price = models.ForeignKey(Price, models.CASCADE, null=True)

fares/forms.py
from django.db.models import Q, Exists, OuterRef
from django.db.utils import OperationalError
from django.forms import Form, ChoiceField

from .models import FareZone, DistanceMatrixElement


class FaresForm(Form):
    origin = ChoiceField(label="From")
    destination = ChoiceField(label="To")

    def __init__(self, tariffs, *args, **kwargs):
        self.tariffs = tariffs

        if len(tariffs) == 1:
            distance_matrix_elements = tariffs[0].distancematrixelement_set
        else:
            distance_matrix_elements = DistanceMatrixElement.objects.filter(
                tariff__in=tariffs
            )

        start_zones = FareZone.objects.filter(
            Exists(distance_matrix_elements.filter(start_zone=OuterRef("pk")))
        )
        end_zones = FareZone.objects.filter(
            Exists(distance_matrix_elements.filter(end_zone=OuterRef("pk")))
        )

        super().__init__(*args, **kwargs)

        try:
            if start_zones:
                start_zones = [("", "")] + [
                    (zone.id, str(zone)) for zone in start_zones
                ]
            if end_zones:
                end_zones = [("", "")] + [(zone.id, str(zone)) for zone in end_zones]

            self.fields["origin"].choices = start_zones
            self.fields["destination"].choices = end_zones
        except OperationalError:
            return

    def get_results(self):
        return (
            DistanceMatrixElement.objects.filter(
                Q(
                    start_zone=self.cleaned_data["origin"],
                    end_zone=self.cleaned_data["destination"],
                )
                | Q(
                    start_zone=self.cleaned_data["destination"],
                    end_zone=self.cleaned_data["origin"],
                ),
                tariff__in=self.tariffs,
            )
            .select_related("price", "tariff", "start_zone", "end_zone")
            .order_by("start_zone", "tariff")
        )

fares/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.views.generic.detail import DetailView

from busstops.models import Service

from .forms import FaresForm
from .models import DataSet, FareTable, Tariff


def index(request):
    datasets = DataSet.objects.order_by("-datetime")

    return render(
        request,
        "fares_index.html",
        {
            "datasets": datasets,
        },
    )


class DataSetDetailView(DetailView):
    model = DataSet

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data["breadcrumb"] = self.object.operators.all()

        if self.request.GET:
            form = FaresForm(self.object.tariff_set.all(), self.request.GET)
            if form.is_valid():
                context_data["results"] = form.get_results()
        else:
            form = FaresForm(self.object.tariff_set.all())

        context_data["form"] = form
        return context_data


class TariffDetailView(DetailView):
    model = Tariff
    queryset = model.objects.prefetch_related(
        "faretable_set__row_set__cell_set__price",
        "faretable_set__column_set",
        "faretable_set__user_profile",
        "faretable_set__sales_offer_package",
        "price_set__time_interval",
        "price_set__sales_offer_package",
    )

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data["breadcrumb"] = [self.object.source]

        if self.request.GET:
            form = FaresForm([self.object], self.request.GET)
            if form.is_valid():
                context_data["results"] = form.get_results()
        else:
            form = FaresForm([self.object])

        context_data["form"] = form

        return context_data


class FareTableDetailView(DetailView):
    model = FareTable
    queryset = model.objects.prefetch_related(
        "row_set__cell_set__price",
        "column_set",
    )


def service_fares(request, slug):
    service = get_object_or_404(Service, slug=slug)
    tariffs = Tariff.objects.filter(services=service).order_by("name", "valid_between")

    tariffs = tariffs.prefetch_related(
        "faretable_set__row_set__cell_set__price",
        "faretable_set__column_set",
        "faretable_set__user_profile",
        "faretable_set__sales_offer_package",
        "faretable_set__preassigned_fare_product",
    )

    if not tariffs:
        raise Http404

    return render(
        request,
        "service_fares.html",
        {
            "breadcrumb": [service],
            "service": service,
            "tariffs": tariffs,
        },
    )

fares/templates/fares/dataset_detail.html
{% extends 'page.html' %}

{% block fuse %}{% endblock %}

{% block bodyclass %}narrow{% endblock %}

{% load date_range %}

{% block content %}

    <h1>{{ object }}</h1>

    {{ object.credit }}

    {{ object.description|linebreaks }}

    {% if form.fields.origin.choices %}
        <form>
            {{ form.as_p }}

            <input type="submit" value="Find fare">
        </form>

        {% for result in results %}
            {% ifchanged result.start_zone %}<h3>{{ result.start_zone }} to {{ result.end_zone }}</h3>{% endifchanged %}
            <p>{{ result.html }}</p>
        {% endfor %}
    {% endif %}

    <h2>Tariffs</h2>

    {% for tariff in object.tariff_set.all %}
        <p>
            <a href="{{ tariff.get_absolute_url }}">
                {{ tariff }}
                {% if tariff.user_profile_id %} ({{ tariff.user_profile }} {{ tariff.trip_type }}){% endif %}
                {% ifchanged tariff.valid_between %} ({{ tariff.valid_between|date_range }}){% endifchanged %}
            </a>
        </p>
    {% endfor %}

{% endblock content %}

fares/templates/fares/faretable_detail.html
<div class="table-wrapper">
<table class="compact nowrap">
    <tbody>
        {% if not object.is_triangular %}
        <tr class="head">
            <th></th>
            {% for column in object.columns %}
                <th scope="col">{{ column }}</th>
            {% endfor %}
        </tr>
        {% else %}
        <tr>
            <th colspan="{{ object.columns|length|add:1 }}">{{ object.columns.0 }}</th>
        </tr>
        {% endif %}
        {% for row in object.rows %}
            <tr>
                {% if not object.is_triangular %}<th>{{ row }}</th>{% endif %}
                {% for cell in row.cells %}
                    <td>{% if cell %}£{{ cell.price }}{% endif %}</td>
                {% empty %}
                    {% if forloop.counter %}
                        <td colspan="{{ forloop.counter }}"></td>
                    {% endif %}
                {% endfor %}
                {% if object.is_triangular %}<th colspan="{{ row.colspan }}">{{ row }}</th>{% endif %}
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>

fares/templates/fares/tariff_detail.html
{% extends 'page.html' %}

{% block bodyclass %}{% endblock %}

{% load date_range %}

{% block content %}

    <h1>{{ object }}</h1>

    <p>{{ object.filename }}</p>

    <p>{{ object.code }}</p>

    <p>{{ object.valid_between|date_range }}</p>

    {% for service in object.services.all %}
        <p><a href="{{ service.get_absolute_url }}/fares">{{ service }}</a></p>
    {% endfor %}

    {% if form.fields.origin.choices %}
        <form autocomplete="off">
            {{ form.as_p }}

            <input type="submit" value="Find fare">
        </form>

        {% for result in results %}
            {% ifchanged result.start_zone %}<h3>{{ result.start_zone }} to {{ result.end_zone }}</h3>{% endifchanged %}
            <p>{{ result.html }}</p>
        {% endfor %}
    {% endif %}

    {% for price in object.price_set.all %}

        <p>{{ price.sales_offer_package }}:<br>{{ price.time_interval.name }} ({{ price.time_interval }}):<br>£{{ price.amount }}</p>

    {% endfor %}

    {% for zone in object.access_zones.all %}
        <p>{{ zone }}</p>
        <p>{{ zone.stops.all }}</p>
    {% endfor %}

    {% for table in object.faretable_set.all %}

        {% ifchanged table.name %}<h2>{{ table }}</h2>{% endifchanged %}

        <p>{% if table.preassigned_fare_product %}
            {{ table.preassigned_fare_product.name }}
        {% elif table.user_profile %}
            {{ table.user_profile|capfirst }} {{ table.sales_offer_package|lower }}
        {% elif table.sales_offer_package %}
            {{ table.sales_offer_package }}
        {% endif %}</p>


        {% include "fares/faretable_detail.html" with object=table %}
    {% endfor %}

    {{ object.source.credit }}

{% endblock content %}