buses/urls.py
from django.urls import include, path
from django.contrib import admin
from api import api

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api/", include(api.router.urls)),
    path("", include("busstops.urls")),
]


handler404 = "busstops.views.not_found"
handler500 = "busstops.views.error"

bustimes/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path("services/<slug>/debug", views.ServiceDebugView.as_view()),
    path("sources", views.SourceListView.as_view()),
    path("sources/<int:pk>", views.SourceDetailView.as_view(), name="source_detail"),
    re_path(
        r"^sources/(?P<source>\d+)/routes/(?P<code>.*)",
        views.route_xml,
        name="route_xml",
    ),
    path("stops/<atco_code>/times.json", views.stop_times_json),
    path("stops/<atco_code>/debug", views.stop_debug),
    path("vehicles/tfl/<reg>", views.tfl_vehicle, name="tfl_vehicle"),
    path("trips/<int:pk>", views.TripDetailView.as_view(), name="trip_detail"),
    path("trips/<int:pk>/block", views.trip_block, name="block_detail"),
    path("trip_updates", views.trip_updates),
]

vosa/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("licences/<slug>", views.LicenceView.as_view(), name="licence_detail"),
    path(
        "registrations/<path:slug>",
        views.RegistrationView.as_view(),
        name="registration_detail",
    ),
    path("licences/<licence_number>/rss", views.LicenceFeed()),
    path("areas/<licence_number>/rss", views.AreaFeed()),
]

bustimes/models.py
from datetime import timedelta
from itertools import pairwise

from django.contrib.gis.db import models
from django.db.models import Q
from django.db.models.functions import Upper
from django.urls import reverse
from django.utils.timezone import localdate

from .fields import SecondsField
from .formatting import format_timedelta, time_datetime


class TimetableDataSource(models.Model):
    name = models.CharField(max_length=255)
    search = models.CharField(max_length=255, blank=True)
    url = models.URLField(blank=True)
    modified_at = models.DateTimeField(null=True, blank=True)
    operators = models.ManyToManyField("busstops.Operator", blank=True)
    settings = models.JSONField(null=True, blank=True)
    complete = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    region = models.ForeignKey(
        "busstops.Region", models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return self.name


class Route(models.Model):
    source = models.ForeignKey("busstops.DataSource", models.CASCADE)
    code = models.CharField(max_length=255, blank=True)  # qualified filename
    service_code = models.CharField(max_length=255, blank=True)
    registration = models.ForeignKey(
        "vosa.Registration", models.SET_NULL, null=True, blank=True
    )
    line_brand = models.CharField(max_length=255, blank=True)
    line_name = models.CharField(max_length=255, blank=True)
    revision_number = models.PositiveIntegerField(default=0)
    description = models.CharField(max_length=255, blank=True)
    outbound_description = models.CharField(max_length=255, blank=True)
    inbound_description = models.CharField(max_length=255, blank=True)
    origin = models.CharField(max_length=255, blank=True)
    destination = models.CharField(max_length=255, blank=True)
    via = models.CharField(max_length=255, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    service = models.ForeignKey(
        "busstops.Service", models.CASCADE, null=True, blank=True
    )
    public_use = models.BooleanField(null=True)

    def contains(self, date):
        if not self.start_date or self.start_date <= date:
            if not self.end_date or self.end_date >= date:
                return True

    class Meta:
        unique_together = ("source", "code")
        indexes = [
            models.Index(fields=("start_date", "end_date")),
            models.Index(fields=("source", "service_code")),
            models.Index(Upper("line_name"), name="route_line_name"),
        ]

    def __str__(self):
        return " – ".join(
            part for part in (self.line_name, self.line_brand, self.description) if part
        )

    def get_absolute_url(self):
        return reverse("route_xml", args=(self.source_id, self.code.split("#")[0]))


class RouteLink(models.Model):
    service = models.ForeignKey("busstops.Service", models.CASCADE)
    from_stop = models.ForeignKey(
        "busstops.StopPoint", models.CASCADE, related_name="link_from"
    )
    to_stop = models.ForeignKey(
        "busstops.StopPoint", models.CASCADE, related_name="link_to"
    )
    distance_metres = models.PositiveSmallIntegerField(null=True, blank=True)
    geometry = models.LineStringField()
    override = models.BooleanField(default=False)

    class Meta:
        unique_together = ("service", "from_stop", "to_stop")

    def __repr__(self):
        return f"<RouteLink: {self.pk} {self.service_id} {self.from_stop_id} {self.to_stop_id}>"


class BankHoliday(models.Model):
    id = models.SmallAutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=255)

    def __str__(self):
        return self.name


class BankHolidayDate(models.Model):
    bank_holiday = models.ForeignKey(BankHoliday, models.CASCADE)
    date = models.DateField()
    scotland = models.BooleanField(
        null=True, help_text="Yes = Scotland only, No = not Scotland, Unknown = both"
    )


class CalendarBankHoliday(models.Model):
    operation = models.BooleanField()
    bank_holiday = models.ForeignKey(BankHoliday, models.CASCADE)
    calendar = models.ForeignKey("bustimes.Calendar", models.CASCADE)

    class Meta:
        unique_together = ("bank_holiday", "calendar")

    def __str__(self):
        if self.operation:
            return str(self.bank_holiday)
        return f"not {self.bank_holiday}"


day_keys = (
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
)


class Calendar(models.Model):
    mon = models.BooleanField()
    tue = models.BooleanField()
    wed = models.BooleanField()
    thu = models.BooleanField()
    fri = models.BooleanField()
    sat = models.BooleanField()
    sun = models.BooleanField()
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    summary = models.CharField(max_length=255, blank=True)
    bank_holidays = models.ManyToManyField(BankHoliday, through=CalendarBankHoliday)
    source = models.ForeignKey(
        "busstops.DataSource", models.CASCADE, null=True, blank=True
    )

    contains = Route.contains

    class Meta:
        indexes = [models.Index(fields=["start_date", "end_date"])]

    def is_sufficiently_simple(self, today, future) -> bool:
        if self.summary or all(
            date.start_date > future or date.end_date and date.end_date < today
            for date in self.calendardate_set.all()
        ):
            if str(self):
                return True
        return False

    def allows(self, date) -> bool:
        if not self.contains(date):
            return False

        if getattr(self, f"{date:%a}".lower()):
            for calendar_date in self.calendardate_set.all():
                if not calendar_date.operation and calendar_date.contains(date):
                    return False
            return True

        for calendar_date in self.calendardate_set.all():
            if (
                calendar_date.operation
                and calendar_date.special
                and calendar_date.contains(date)
            ):
                return True

        if date in self.bank_holiday_exclusions:
            return False
        if date in self.bank_holiday_inclusions:
            return True

    def get_days(self) -> list:
        day_values = (
            self.mon,
            self.tue,
            self.wed,
            self.thu,
            self.fri,
            self.sat,
            self.sun,
        )
        return [day_keys[i] for i, value in enumerate(day_values) if value]

    def get_order(self) -> list:
        return [day_keys.index(day) for day in self.get_days()]

    def describe_for_timetable(self, today=None) -> str:
        start_date = self.start_date
        end_date = self.end_date

        for i in range(0, 6):
            if not self.allows(start_date):
                start_date += timedelta(days=1)

        if end_date:
            for calendar_date in self.calendardate_set.all():
                if (
                    not calendar_date.operation
                    and calendar_date.end_date >= end_date
                    and calendar_date.start_date <= end_date
                ):
                    # "until 30 may 2020, but not from 20 may to 30 may" - simplify to "until 19 may"
                    end_date = calendar_date.start_date - timedelta(days=1)

            for i in range(0, 6):
                if not self.allows(end_date):
                    end_date -= timedelta(days=1)

            if start_date == end_date:
                return f"{start_date:%A %-d %B %Y} only"

        description = str(self)

        if self.bank_holiday_inclusions and not self.bank_holiday_exclusions:
            description = f"{description} and bank holidays"
        elif self.bank_holiday_exclusions and not self.bank_holiday_inclusions:
            for date in self.bank_holiday_exclusions:
                if getattr(self, f"{date:%a}".lower()):
                    description = f"{description} (not bank holidays)"
                    break

        if not today:
            today = localdate()

        for cd in self.calendardate_set.all():
            if (
                cd.start_date == cd.end_date
                and cd.start_date >= today
                and cd.start_date - today < timedelta(days=21)
            ):
                if cd.operation and not getattr(self, f"{cd.start_date:%a}".lower()):
                    description = f"{description} (and {cd.start_date:%A %-d %B})"
                elif not cd.operation and getattr(self, f"{cd.start_date:%a}".lower()):
                    description = f"{description} (not {cd.start_date:%A %-d %B})"

        if self.start_date > today:
            description = f"{description} from {start_date:%A %-d %B %Y}"
        if end_date and (
            end_date - today < timedelta(days=21)
            or end_date - start_date < timedelta(days=200)
        ):
            description = f"{description} until {end_date:%A %-d %B %Y}"

        return description

    def __str__(self):
        days = self.get_days()
        if not days:
            return self.summary
        if len(days) == 1:
            days = f"{days[0]}s"
        elif (
            len(days) > 2
            and day_keys.index(days[-1]) - day_keys.index(days[0]) == len(days) - 1
        ):
            days = f"{days[0]} to {days[-1]}"
        else:
            days = f"{'s, '.join(days[:-1])}s and {days[-1]}s"

        if self.summary:
            return f"{days}, {self.summary}"

        return days


class CalendarDate(models.Model):
    calendar = models.ForeignKey(Calendar, models.CASCADE)
    start_date = models.DateField(db_index=True)
    end_date = models.DateField(null=True, blank=True, db_index=True)
    operation = models.BooleanField(db_index=True)
    special = models.BooleanField(default=False, db_index=True)

bustimes/templates/service_debug.html
{% extends 'page.html' %}

{% block title %}Debug – {{ object }} – timesbus.org{% endblock %}

{% block canonical %}<meta name="robots" content="noindex,noarchive">{% endblock %}

{% block bodyclass %}{% endblock %}

{% block content %}

<h1>{{ object }}</h1>

<ul class="tabs">
    <li><a href="{{ object.get_absolute_url }}">Timetable</a></li>
    <li><a href="{{ object.get_absolute_url }}/vehicles">Vehicles</a></li>
    <li>Debug</li>
    <li><a href="{% url 'admin:busstops_service_change' object.pk %}">Edit</a></li>
</ul>

<pre>{{ object.yaml }}</pre>

{% if service.servicecode_set.all %}
    <h2>Service codes</h2>

    <table>
        <thead>
            <tr><th>Scheme</th><th>Code</th>
        </thead>
        <tbody>
            {% for code in service.servicecode_set.all %}
                <tr><td>{{ code.scheme }}</td><td>{{ code.code }}</td></tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

<h2>Routes</h2>

{% for route in routes %}

<details{% if forloop.first and forloop.last %} open{% endif %}>
    <summary>
        <a href="{{ route.source.get_absolute_url }}">{{ route.source }}</a>/<a href="{{ route.get_absolute_url }}">{{ route.code }}</a>
        <br>ServiceCode: {{ route.service_code }}
        <br>RevisionNumber: {{ route.revision_number }}
        <br>OperatingPeriod: {{ route.start_date }}–{{ route.end_date }}
        <br>{{ route.description }}
        <br>{{ route.origin }} to {{ route.destination }} via {{ route.via }}

        <br><a href="{% url 'admin:bustimes_route_change' route.id %}">Edit</a>
    </summary>

<table>
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Block</th>
            <th scope="col">Code</th>
            <th scope="col">Direction</th>
            <th scope="col">Start</th>
            <th scope="col">End</th>
            <th scope="col">Dates</th>
            <th scope="col">Days</th>
            <th scope="col">Bank Holidays</th>
            <th scope="col">Dates</th>
            <th scope="col">Garage</th>
        </tr>
    </thead>
    <tbody>
{% for trip in route.trip_set.all %}
<tr style="vertical-align:top">
    <td>{% if trip.sequence %}{{ trip.sequence }}{% endif %}</td>
    <td class="link">{% if trip.block %}<a href="{{ trip.get_absolute_url }}/block">{{ trip.block }}</a>{% endif %}</td>
    <td>{% firstof trip.ticket_machine_code trip.vehicle_journey_code %}</td>
    <td>{% if trip.inbound %}in{% else %}out{% endif %}</td>
    <td class="link"><a href="{{ trip.get_absolute_url }}">{{ trip.start }}</a></td>
    <td>{{ trip.end }}</td>
    {% if trip.rowspan and trip.calendar %}
        <td rowspan="{{ trip.rowspan }}">{{ trip.calendar.start_date }}–<br>{{ trip.calendar.end_date }}</td>
        <td rowspan="{{ trip.rowspan }}" class="link"><a href="{% url 'admin:bustimes_calendar_change' trip.calendar.id %}">{{ trip.calendar }}</a></td>
        <td rowspan="{{ trip.rowspan }}">
            {% for bank_holiday in trip.calendar.calendarbankholiday_set.all %}
                {{ bank_holiday }}<br>
            {% endfor %}
        </td>
        <td rowspan="{{ trip.rowspan }}" class="link">
            {% for calendar_date in trip.calendar.calendardate_set.all %}
                <a href="{% url 'admin:bustimes_calendardate_change' calendar_date.id %}">{{ calendar_date }}</a>
            {% endfor %}
        </td>
    {% endif %}
    <td>{% if trip.garage %}{{ trip.garage }}{% endif %}</td>
    <td class="link">
        <a href="{% url 'admin:bustimes_trip_change' trip.pk %}">✎</a>
    </td>
</tr>
{% endfor %}
</tbody>
</table>
</details>
{% endfor %}

{% include 'route.html' %}

{% endblock content %}

bustimes/templates/tfl_vehicle.html
{% extends 'bustimes/trip_detail.html' %}

{% block title %}{{ data.0.lineName }} to {{ data.0.destinationName }} – timesbus.org{% endblock %}

{% load static %}

{% block footer %}
    {{ stops_data|json_script:"trip-data" }}
    {% if object %}
        <script>window.VEHICLE_ID = {{ object.id }};</script>
    {% endif %}
    <script src="{% static 'dist/js/app.js' %}"></script>
{% endblock footer %}

bustimes/templates/trip_updates.html
{% extends 'page.html' %}

{% block title %}trip updates{% endblock %}

{% block bodyclass %}{% endblock %}

{% block breadcrumb %}{% endblock %}

{% block content %}

<h1>{{ trip_updates|length }} trip_updates</h1>

<p>{{ trips }} matching trips</p>

<p>{{ operators }}</p>

<p>{{ timestamp }}</p>

{% for entity, trip in trip_updates %}
    <details>
        <summary>
            {{ entity.tripUpdate.trip.tripId }}
            {% if trip %}
                <a href="{{ trip.get_absolute_url }}">{{ trip }}</a>
            {% endif %}
            {{ entity.tripUpdate.trip.scheduleRelationship }}
        </summary>
        <code>{{ entity }}</code>
    </details>
{% endfor %}

{% endblock content %}