buses/urls.py
from django.urls import include, path
from django.contrib import admin
from api import api

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api/", include(api.router.urls)),
    path("", include("busstops.urls")),
]


handler404 = "busstops.views.not_found"
handler500 = "busstops.views.error"

vosa/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("licences/<slug>", views.LicenceView.as_view(), name="licence_detail"),
    path(
        "registrations/<path:slug>",
        views.RegistrationView.as_view(),
        name="registration_detail",
    ),
    path("licences/<licence_number>/rss", views.LicenceFeed()),
    path("areas/<licence_number>/rss", views.AreaFeed()),
]

vosa/models.py
from django.db import models
from django.db.models import Count
from django.urls import reverse


class TrafficArea(models.TextChoices):
    WEST = "H", "West of England"
    WM = "D", "West Midlands"
    WALES = "G", "Wales"
    SE = "K", "London and the South East of England"
    SCOTLAND = "M", "Scotland"
    NW = "C", "North West of England"
    NE = "B", "North East of England"
    EAST = "F", "East of England"


class Description(models.TextChoices):
    RESTRICTED = "Restricted"
    STANDARD_INTERNATIONAL = "Standard International"
    STANDARD_NATIONAL = "Standard National"


class Licence(models.Model):
    name = models.CharField(max_length=255)
    trading_name = models.CharField(max_length=255, blank=True)
    traffic_area = models.CharField(max_length=1, choices=TrafficArea.choices)
    licence_number = models.CharField(max_length=20, unique=True)
    discs = models.PositiveSmallIntegerField()
    authorised_discs = models.PositiveSmallIntegerField()
    description = models.CharField(max_length=22, choices=Description.choices)
    granted_date = models.DateField(null=True, blank=True)
    expiry_date = models.DateField(null=True, blank=True)
    address = models.TextField()
    licence_status = models.CharField(max_length=255, blank=True)

    def get_operators(self):
        return (
            self.operator_set.annotate(services=Count("service", current=True))
            .filter(services__gt=0)
            .order_by("-services")
        )

    def __str__(self):
        return self.licence_number

    def get_absolute_url(self):
        return reverse("licence_detail", args=(self.licence_number,))


class Registration(models.Model):
    licence = models.ForeignKey(Licence, models.CASCADE)
    registration_number = models.CharField(max_length=20, unique=True)
    service_number = models.CharField(max_length=100, blank=True)
    start_point = models.CharField(max_length=255, blank=True)
    finish_point = models.CharField(max_length=255, blank=True)
    via = models.CharField(blank=True, max_length=255)
    subsidies_description = models.CharField(max_length=255)
    subsidies_details = models.CharField(max_length=255, blank=True)
    service_type_description = models.CharField(max_length=255, blank=True)
    registration_status = models.CharField(max_length=255, db_index=True)
    traffic_area_office_covered_by_area = models.CharField(max_length=100)
    authority_description = models.CharField(max_length=255, blank=True)
    registered = models.BooleanField()
    latest_variation = models.ForeignKey(
        "Variation", models.SET_NULL, null=True, blank=True, related_name="latest"
    )

    def __str__(self):
        string = "{} - {} to {}".format(
            self.service_number, self.start_point, self.finish_point
        )
        if self.via:
            string = "{} via {}".format(string, self.via)
        return string

    def get_absolute_url(self):
        return reverse("registration_detail", args=(self.registration_number,))


class Variation(models.Model):
    registration = models.ForeignKey(Registration, models.CASCADE)
    variation_number = models.PositiveSmallIntegerField()
    effective_date = models.DateField(null=True, blank=True)
    date_received = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    service_type_other_details = models.TextField()
    registration_status = models.CharField(max_length=255)
    publication_text = models.TextField()
    short_notice = models.CharField(max_length=255)

    class Meta:
        ordering = ("-variation_number",)
        unique_together = ("registration", "variation_number")

    def __str__(self):
        return str(self.registration)

    def get_absolute_url(self):
        url = reverse(
            "registration_detail", args=(self.registration.registration_number,)
        )
        url = f"{url}#{self.variation_number}"
        return url

vosa/views.py
from datetime import datetime

from django.contrib.syndication.views import Feed
from django.db.models import Exists, Max, OuterRef
from django.views.generic.detail import DetailView

from busstops.models import Service
from busstops.views import get_colours
from bustimes.models import Route

from .models import Licence, Registration, Variation


class UpperCaseSlugMixin:
    def get_object(self):
        self.kwargs["slug"] = self.kwargs["slug"].upper()
        return super().get_object()


class LicenceView(UpperCaseSlugMixin, DetailView):
    model = Licence
    slug_field = "licence_number"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        registrations = self.object.registration_set.annotate(
            effective_date=Max("variation__effective_date"),
            received_date=Max("variation__date_received"),
        ).order_by("-effective_date", "-received_date")

        context["registrations"] = registrations.filter(registered=True)
        context["cancelled"] = registrations.filter(registered=False)

        operators = self.object.get_operators()
        if operators:
            context["operators"] = operators
            context["breadcrumb"] = [operators[0].region, operators[0]]

        return context


class RegistrationView(UpperCaseSlugMixin, DetailView):
    model = Registration
    slug_field = "registration_number"
    queryset = model.objects.select_related("licence")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["variations"] = self.object.variation_set.all()

        context["breadcrumb"] = [self.object.licence]

        operators = self.object.licence.get_operators()
        if operators:
            context["breadcrumb"] = [
                operators[0].region,
                operators[0],
            ] + context["breadcrumb"]

        services = Service.objects.with_line_names().filter(
            Exists(
                Route.objects.filter(service=OuterRef("id"), registration=self.object)
            ),
            current=True,
        )
        context["services"] = sorted(services, key=Service.get_order)
        if context["services"]:
            context["colours"] = get_colours(context["services"])

        return context


class LicenceFeed(Feed):
    description_template = "rss_description.html"

    def get_object(self, request, licence_number):
        return Licence.objects.get(licence_number=licence_number)

    def title(self, obj):
        return f"{obj} – {obj.name}"

    def link(self, obj):
        return obj.get_absolute_url()

    def items(self, obj):
        items = Variation.objects.filter(registration__licence=obj).exclude(
            date_received=None
        )
        return items.select_related("registration").order_by("-date_received")[:100]

    def item_pubdate(self, item):
        date = item.date_received
        return datetime(date.year, date.month, date.day)


class AreaFeed(Feed):
    pass

vosa/templates/vosa/licence_detail.html
{% extends 'page.html' %}

{% block title %}{{ object }} – {{ object.name }} – timesbus.org{% endblock %}

{% block head %}
<link rel="alternate" type="application/rss+xml" href="{{ object.get_absolute_url }}/rss" title="RSS feed for {{ object }} – {{ object.name }}">
{% endblock head %}

{% block content %}

<h1>{{ object }}</h1>

{% if operators %}
    <p>({% for operator in operators %}<a href="{{ operator.get_absolute_url }}">{{ operator }}</a>{% if not forloop.last %}, {% endif %}{% endfor %})</p>
{% endif %}

<table>
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
        {% if object.trading_name %}
            <tr>
                <th>Trading name</th>
                <td>{{ object.trading_name|linebreaksbr }}</td>
            </tr>
        {% endif %}
        <tr>
            <th>Licence type</th>
            <td>{{ object.description }}</td>
        </tr>
        <tr>
            <th>Traffic area</th>
            <td>{{ object.get_traffic_area_display }}</td>
        </tr>
        <tr>
            <th>Discs</th>
            <td>{{ object.discs }}</td>
        </tr>
        <tr>
            <th>Authorised discs</th>
            <td>{{ object.authorised_discs }}</td>
        </tr>
        <tr>
            <th>Address</th>
            <td>{{ object.address }}</td>
        </tr>
        {% if object.granted_date %}
            <tr>
                <th>Granted date</th>
                <td>{{ object.granted_date }}</td>
            </tr>
        {% endif %}
        {% if object.expiry_date %}
            <tr>
                <th>Expiry date</th>
                <td>{{ object.expiry_date }}</td>
            </tr>
        {% endif %}
    </tbody>
</table>

<p class="credit">Powered by <a href="https://www.data.gov.uk/dataset/9ea90ed8-de54-4274-92c6-272edd518bfb/traffic-commissioners-local-bus-service-registration">Traffic Commissioners’ local bus service registration data</a></p>

<p><a href="{{ object.get_absolute_url }}/rss">RSS feed</a></p>

{% if registrations %}
    <h2>Current and future bus service registrations</h2>

    <table>
        <thead>
            <tr>
                <th colspan="2"></th>
                <th scope="col">From</th>
                <th scope="col">To</th>
                <th scope="col">Via</th>
                <th scope="col">Last changed</th>
            </tr>
        </thead>
        <tbody>
            {% for registration in registrations %}
                <tr>
                    <td><a href="{{ registration.get_absolute_url }}">{{ registration.registration_number }}</a></td>
                    <td>{{ registration.service_number }}</td>
                    <td>{{ registration.start_point }}</td>
                    <td>{{ registration.finish_point }}</td>
                    <td>{{ registration.via }}</td>
                    <td>{{ registration.effective_date|date:"j M y" }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

{% if cancelled %}
    <h2>Cancelled bus service registrations</h2>

    <table>
        <thead>
            <tr>
                <th colspan="2"></th>
                <th scope="col">From</th>
                <th scope="col">To</th>
                <th scope="col">Via</th>
                <th scope="col">Cancelled</th>
            </tr>
        </thead>
        <tbody>
            {% for registration in cancelled %}
                <tr>
                    <td><a href="{{ registration.get_absolute_url }}">{{ registration.registration_number }}</a></td>
                    <td>{{ registration.service_number }}</td>
                    <td>{{ registration.start_point }}</td>
                    <td>{{ registration.finish_point }}</td>
                    <td>{{ registration.via }}</td>
                    <td>{{ registration.effective_date|date:"j M y" }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

{% endblock content %}

vosa/templates/vosa/registration_detail.html
{% extends 'page.html' %}

{% block title %}{{ object.registration_number }} – timesbus.org{% endblock %}

{% block bodyclass %}narrow{% endblock %}

{% block content %}

<h1>{{ object }}</h1>

<div class="asides">
    <div class="aside">
        <dl>
            <dt>Registration number</dt>
            <dd>{{ object.registration_number }}</dd>

            <dt>Type</dt>
            <dd>{{ object.service_type_description|linebreaksbr }}</dd>

            <dt>Supported by subsidy?</dt>
            <dd>{{ object.subsidies_description }}{% if object.subsidies_details %}<br>
                    {{ object.subsidies_details|linebreaksbr }}
                {% endif %}
            </dd>

            <dt>Authorities</dt>
            <dd>{{ object.authority_description|linebreaksbr }}</dd>
        </dl>
    </div>

    {% if services %}
        <div class="aside">
            <h2>Timetables</h2>

            {% include 'service_list.html' with services=services class="has-smalls" %}
        </div>
    {% endif %}
</div>

<h2>Variation history</h2>

<ol class="history">
    {% for variation in variations %}
        <li value="{{ variation.variation_number }}">
        {% if variation.registration_status == "Withdrawn" or variation.registration_status == "Expired" %}<del>{% endif %}
            <ul>
                {% if variation.date_received %}<li>
                    <strong>Received</strong>
                    {{ variation.date_received|date:"j M y" }}
                </li>{% endif %}

                {% if variation.effective_date %}<li>
                    <strong>Effective</strong>
                    {{ variation.effective_date|date:"j M y" }}
                </li>{% endif %}

                {% if variation.end_date %}<li>
                    <strong>End</strong>
                    {{ variation.end_date|date:"j M y" }}
                </li>{% endif %}

                <li>
                    {{ variation.registration_status }}
                </li>

                {% if variation.short_notice == 'Yes' %}<li>
                    Short notice
                </li>{% endif %}
            </ul>

            {{ variation.service_type_other_details|linebreaks }}

            {{ variation.publication_text|linebreaks }}
        </li>
        {% if variation.registration_status == "Withdrawn" or variation.registration_status == "Expired" %}</del>{% endif %}
    {% endfor %}
</ol>

<p class="credit">Powered by <a href="https://www.data.gov.uk/dataset/9ea90ed8-de54-4274-92c6-272edd518bfb/traffic-commissioners-local-bus-service-registration">Traffic Commissioners’ local bus service registration data</a></p>

{% endblock content %}